# Copyright 2026 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Migration Estimator Tool for Microsoft Graph data estimation.

This application allows users to estimate the time and resources required to
migrate data from Microsoft 365 to Google Workspace. It connects to the
Microsoft Graph API to fetch user, email, contact, and calendar data counts.

DISCLAIMER
==========
The estimations provided by this tool are calculated projections intended for
preliminary planning only.
Actual migration timelines (ETAs) and batch execution may vary based on
real-time network conditions, source/target throttling policies, migration
configurations, and the volume of delta migrations.
The estimations do not constitute a performance guarantee or a binding service
level agreement (SLA).
Please note that this release is an experimental feature with limited and
evolving functionality.
Partners and/or Customers should NOT use this product for production projects
where business outcomes rely on the product functionality or timelines.
Partners and/or Customers should NOT commit hard migration timelines based on
this product.
By using this tool, you acknowledge that log files generated by this script
contain personally identifiable information and that you are solely responsible
for securing your local environment and these files.
Use of this tool is governed by the Apache 2.0 license.

Functionality Limitations
=========================
This tool only provides migration time estimates for the new Data Migration
Service with specific enhancements for large scale migrations. It does not cover
Google Workspace Migrate, or any other data migration tool.
Only Microsoft Exchange Online scan and migration planning is supported. And
ETAs are based on Email corpus only.
This tool only provides a guesstimate, and migration timelines should in no way
be taken as guarantee or SLA.
"""

import os
import urllib3
from ui.files_ui import FileMigrationEstimatorTool
from ui.exchange_online_ui import MigrationEstimatorTool

def main():
  """Application entry point."""
  # Suppress SSL warnings for cleaner console output
  urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

  # Configure High DPI scaling if necessary (Windows)
  try:
    from ctypes import windll

    windll.shcore.SetProcessDpiAwareness(1)
  except Exception:
    pass

  tool_type = os.environ.get("MIGRATION_TOOL_TYPE", "exchange")
  if tool_type == "files":
    app = FileMigrationEstimatorTool()
  else:
    app = MigrationEstimatorTool()
  app.mainloop()


if __name__ == "__main__":
  main()
